# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-13 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_record_patient_readable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='role',
            field=models.CharField(choices=[('DR', 'Doctor'), ('PT', 'Patient'), ('AD', 'Admin')], default='PT', max_length=2),
        ),
    ]
