# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-13 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_auto_20170113_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='role',
            field=models.CharField(choices=[('BU', 'Doctor'), ('SE', 'Patient'), ('AD', 'Admin')], default='SE', max_length=2),
        ),
    ]
