# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-13 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_auto_20170113_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='primary_care',
        ),
        migrations.AlterField(
            model_name='registration',
            name='role',
            field=models.CharField(choices=[('SE', 'Seller'), ('BU', 'Buyer'), ('AD', 'Admin')], default='BU', max_length=2),
        ),
    ]
