# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-15 02:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_auto_20170113_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='record',
            name='seller',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
