# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-16 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_auto_20170114_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_buyer', to='system.Registration'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_seller', to='system.Registration'),
        ),
    ]
