# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-16 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_auto_20170116_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='text',
        ),
    ]
