# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-16 23:38
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_remove_item_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('NE', 'NEW'), ('NM', 'Near Mint'), ('SU', 'Slightly Used'), ('US', 'Used'), ('WO', 'Worn')], default='NM', max_length=2),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
