# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-16 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_auto_20170116_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('NE', 'New'), ('NM', 'Near Mint or Better'), ('UP', 'Used or Pre-owned'), ('LU', 'Lightly Used'), ('MU', 'Moderately Used'), ('NS', 'Not Specified')], default='NM', max_length=2),
        ),
    ]
