# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-18 00:53
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0025_auto_20170116_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.TextField()),
                ('condition', models.CharField(choices=[('NE', 'New'), ('NM', 'Near Mint or Better'), ('UP', 'Used or Pre-owned'), ('LU', 'Lightly Used'), ('MU', 'Moderately Used'), ('NS', 'Not Specified')], default='NM', max_length=2)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('claimer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claimed_item', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
