# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-18 00:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0026_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='claimer',
            new_name='buyer',
        ),
    ]
